jobs:
  include:
    - language: objective-c
      os: osx
      osx_image: xcode11.5
      install:
        - pip3 install meson
      addons:
        homebrew:
          packages:
            - ninja
            - llvm
            - libarchive
          update: true
      script:
        - xcodebuild -project iSH.xcodeproj -scheme iSH -sdk iphonesimulator CODE_SIGNING_ALLOWED=NO
