jobs:
  include:
    - language: objective-c
      os: osx
      osx_image: xcode11.5
      install:
        - pip3 install meson
      addons:
        homebrew:
          packages:
            - python@3.8
            - ninja
            - llvm
            - libarchive
          update: true
      script:
        - xcodebuild -project iSH.xcodeproj -scheme iSH -sdk iphonesimulator CODE_SIGNING_ALLOWED=NO
        
addons:
  artifacts:
    s3_region: "ap-southeast-1" # defaults to "us-east-1"
    debug: true
     
